'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace IESB_AV_ServicioMensajes
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="IESB_AV_ServicioMensajesSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class IESB_AV_ServicioMensajes
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarCorreoElectronico_Mail_OldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronico_MailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronico_SQL_ServerOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnvioCorreoElectronico_AFEXOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronico_Mail_2_OldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronico_Mail_2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronicoAdjuntos_OldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnvioCorreoElectronico_EstandarSQL_OldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnvioCorreoElectronico_AplicacionSQLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronico_Asincrono_OldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronicoAdjuntosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnvioCorreoElectronico_EstandarSQLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoElectronico_AsincronoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarCorreoSESOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnvioCorreoElectronico_PortalOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarMensajeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ComentarMensajeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerMensajesActualizadosTOP20OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ObtenerDestinatariosMensajeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.AgenteAFEXTI.My.MySettings.Default.winPublicadorAFEX_IESB_AV_ServicioMensajes_IESB_AV_ServicioMensajes
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarCorreoElectronico_Mail_OldCompleted As EnviarCorreoElectronico_Mail_OldCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronico_MailCompleted As EnviarCorreoElectronico_MailCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronico_SQL_ServerCompleted As EnviarCorreoElectronico_SQL_ServerCompletedEventHandler
        
        '''<remarks/>
        Public Event EnvioCorreoElectronico_AFEXCompleted As EnvioCorreoElectronico_AFEXCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronico_Mail_2_OldCompleted As EnviarCorreoElectronico_Mail_2_OldCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronico_Mail_2Completed As EnviarCorreoElectronico_Mail_2CompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronicoAdjuntos_OldCompleted As EnviarCorreoElectronicoAdjuntos_OldCompletedEventHandler
        
        '''<remarks/>
        Public Event EnvioCorreoElectronico_EstandarSQL_OldCompleted As EnvioCorreoElectronico_EstandarSQL_OldCompletedEventHandler
        
        '''<remarks/>
        Public Event EnvioCorreoElectronico_AplicacionSQLCompleted As EnvioCorreoElectronico_AplicacionSQLCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronico_Asincrono_OldCompleted As EnviarCorreoElectronico_Asincrono_OldCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronicoAdjuntosCompleted As EnviarCorreoElectronicoAdjuntosCompletedEventHandler
        
        '''<remarks/>
        Public Event EnvioCorreoElectronico_EstandarSQLCompleted As EnvioCorreoElectronico_EstandarSQLCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoElectronico_AsincronoCompleted As EnviarCorreoElectronico_AsincronoCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarCorreoSESCompleted As EnviarCorreoSESCompletedEventHandler
        
        '''<remarks/>
        Public Event EnvioCorreoElectronico_PortalCompleted As EnvioCorreoElectronico_PortalCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarMensajeCompleted As EnviarMensajeCompletedEventHandler
        
        '''<remarks/>
        Public Event ComentarMensajeCompleted As ComentarMensajeCompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerMensajesActualizadosTOP20Completed As ObtenerMensajesActualizadosTOP20CompletedEventHandler
        
        '''<remarks/>
        Public Event ObtenerDestinatariosMensajeCompleted As ObtenerDestinatariosMensajeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronico_Mail_Old", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronico_Mail_Old(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronico_Mail_Old", New Object() {Destinatarios, Asunto, Cuerpo, Formato, TipoServicio})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Mail_OldAsync(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio)
            Me.EnviarCorreoElectronico_Mail_OldAsync(Destinatarios, Asunto, Cuerpo, Formato, TipoServicio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Mail_OldAsync(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio, ByVal userState As Object)
            If (Me.EnviarCorreoElectronico_Mail_OldOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronico_Mail_OldOperationCompleted = AddressOf Me.OnEnviarCorreoElectronico_Mail_OldOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronico_Mail_Old", New Object() {Destinatarios, Asunto, Cuerpo, Formato, TipoServicio}, Me.EnviarCorreoElectronico_Mail_OldOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronico_Mail_OldOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronico_Mail_OldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronico_Mail_OldCompleted(Me, New EnviarCorreoElectronico_Mail_OldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronico_Mail", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronico_Mail(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronico_Mail", New Object() {Destinatarios, Asunto, Cuerpo, Formato, TipoServicio})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_MailAsync(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio)
            Me.EnviarCorreoElectronico_MailAsync(Destinatarios, Asunto, Cuerpo, Formato, TipoServicio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_MailAsync(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio, ByVal userState As Object)
            If (Me.EnviarCorreoElectronico_MailOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronico_MailOperationCompleted = AddressOf Me.OnEnviarCorreoElectronico_MailOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronico_Mail", New Object() {Destinatarios, Asunto, Cuerpo, Formato, TipoServicio}, Me.EnviarCorreoElectronico_MailOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronico_MailOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronico_MailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronico_MailCompleted(Me, New EnviarCorreoElectronico_MailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronico_SQL_Server", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronico_SQL_Server(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronico_SQL_Server", New Object() {Destinatarios, Asunto, Cuerpo, Formato, TipoServicio})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_SQL_ServerAsync(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio)
            Me.EnviarCorreoElectronico_SQL_ServerAsync(Destinatarios, Asunto, Cuerpo, Formato, TipoServicio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_SQL_ServerAsync(ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio, ByVal userState As Object)
            If (Me.EnviarCorreoElectronico_SQL_ServerOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronico_SQL_ServerOperationCompleted = AddressOf Me.OnEnviarCorreoElectronico_SQL_ServerOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronico_SQL_Server", New Object() {Destinatarios, Asunto, Cuerpo, Formato, TipoServicio}, Me.EnviarCorreoElectronico_SQL_ServerOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronico_SQL_ServerOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronico_SQL_ServerCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronico_SQL_ServerCompleted(Me, New EnviarCorreoElectronico_SQL_ServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioCorreoElectronico_AFEX", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnvioCorreoElectronico_AFEX(ByVal IdAplicacion As Integer, ByVal IdMail As Integer, ByVal IdAmbiente As Integer, ByVal NombrePrefil As String, ByVal MailDestinatario As String, ByVal Rut As String, ByVal NombreCliente As String, ByVal Monto As String, ByVal Moneda As String, ByVal Ejecutivo As String, ByVal CodigoSolicitud As Double) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnvioCorreoElectronico_AFEX", New Object() {IdAplicacion, IdMail, IdAmbiente, NombrePrefil, MailDestinatario, Rut, NombreCliente, Monto, Moneda, Ejecutivo, CodigoSolicitud})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_AFEXAsync(ByVal IdAplicacion As Integer, ByVal IdMail As Integer, ByVal IdAmbiente As Integer, ByVal NombrePrefil As String, ByVal MailDestinatario As String, ByVal Rut As String, ByVal NombreCliente As String, ByVal Monto As String, ByVal Moneda As String, ByVal Ejecutivo As String, ByVal CodigoSolicitud As Double)
            Me.EnvioCorreoElectronico_AFEXAsync(IdAplicacion, IdMail, IdAmbiente, NombrePrefil, MailDestinatario, Rut, NombreCliente, Monto, Moneda, Ejecutivo, CodigoSolicitud, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_AFEXAsync(ByVal IdAplicacion As Integer, ByVal IdMail As Integer, ByVal IdAmbiente As Integer, ByVal NombrePrefil As String, ByVal MailDestinatario As String, ByVal Rut As String, ByVal NombreCliente As String, ByVal Monto As String, ByVal Moneda As String, ByVal Ejecutivo As String, ByVal CodigoSolicitud As Double, ByVal userState As Object)
            If (Me.EnvioCorreoElectronico_AFEXOperationCompleted Is Nothing) Then
                Me.EnvioCorreoElectronico_AFEXOperationCompleted = AddressOf Me.OnEnvioCorreoElectronico_AFEXOperationCompleted
            End If
            Me.InvokeAsync("EnvioCorreoElectronico_AFEX", New Object() {IdAplicacion, IdMail, IdAmbiente, NombrePrefil, MailDestinatario, Rut, NombreCliente, Monto, Moneda, Ejecutivo, CodigoSolicitud}, Me.EnvioCorreoElectronico_AFEXOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnvioCorreoElectronico_AFEXOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnvioCorreoElectronico_AFEXCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnvioCorreoElectronico_AFEXCompleted(Me, New EnvioCorreoElectronico_AFEXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronico_Mail_2_Old", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronico_Mail_2_Old(ByVal MensajeRequest As MensajeRequest) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronico_Mail_2_Old", New Object() {MensajeRequest})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Mail_2_OldAsync(ByVal MensajeRequest As MensajeRequest)
            Me.EnviarCorreoElectronico_Mail_2_OldAsync(MensajeRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Mail_2_OldAsync(ByVal MensajeRequest As MensajeRequest, ByVal userState As Object)
            If (Me.EnviarCorreoElectronico_Mail_2_OldOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronico_Mail_2_OldOperationCompleted = AddressOf Me.OnEnviarCorreoElectronico_Mail_2_OldOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronico_Mail_2_Old", New Object() {MensajeRequest}, Me.EnviarCorreoElectronico_Mail_2_OldOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronico_Mail_2_OldOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronico_Mail_2_OldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronico_Mail_2_OldCompleted(Me, New EnviarCorreoElectronico_Mail_2_OldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronico_Mail_2", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronico_Mail_2(ByVal MensajeRequest As MensajeRequest) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronico_Mail_2", New Object() {MensajeRequest})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Mail_2Async(ByVal MensajeRequest As MensajeRequest)
            Me.EnviarCorreoElectronico_Mail_2Async(MensajeRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Mail_2Async(ByVal MensajeRequest As MensajeRequest, ByVal userState As Object)
            If (Me.EnviarCorreoElectronico_Mail_2OperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronico_Mail_2OperationCompleted = AddressOf Me.OnEnviarCorreoElectronico_Mail_2OperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronico_Mail_2", New Object() {MensajeRequest}, Me.EnviarCorreoElectronico_Mail_2OperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronico_Mail_2OperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronico_Mail_2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronico_Mail_2Completed(Me, New EnviarCorreoElectronico_Mail_2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronicoAdjuntos_Old", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronicoAdjuntos_Old(ByVal MensajeRequest As MensajeAdjuntosRequest) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronicoAdjuntos_Old", New Object() {MensajeRequest})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronicoAdjuntos_OldAsync(ByVal MensajeRequest As MensajeAdjuntosRequest)
            Me.EnviarCorreoElectronicoAdjuntos_OldAsync(MensajeRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronicoAdjuntos_OldAsync(ByVal MensajeRequest As MensajeAdjuntosRequest, ByVal userState As Object)
            If (Me.EnviarCorreoElectronicoAdjuntos_OldOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronicoAdjuntos_OldOperationCompleted = AddressOf Me.OnEnviarCorreoElectronicoAdjuntos_OldOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronicoAdjuntos_Old", New Object() {MensajeRequest}, Me.EnviarCorreoElectronicoAdjuntos_OldOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronicoAdjuntos_OldOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronicoAdjuntos_OldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronicoAdjuntos_OldCompleted(Me, New EnviarCorreoElectronicoAdjuntos_OldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioCorreoElectronico_EstandarSQL_Old", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnvioCorreoElectronico_EstandarSQL_Old(ByVal Destinatario As String, ByVal MailCopia As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnvioCorreoElectronico_EstandarSQL_Old", New Object() {Destinatario, MailCopia, Asunto, Cuerpo, Formato, Importancia})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_EstandarSQL_OldAsync(ByVal Destinatario As String, ByVal MailCopia As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String)
            Me.EnvioCorreoElectronico_EstandarSQL_OldAsync(Destinatario, MailCopia, Asunto, Cuerpo, Formato, Importancia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_EstandarSQL_OldAsync(ByVal Destinatario As String, ByVal MailCopia As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String, ByVal userState As Object)
            If (Me.EnvioCorreoElectronico_EstandarSQL_OldOperationCompleted Is Nothing) Then
                Me.EnvioCorreoElectronico_EstandarSQL_OldOperationCompleted = AddressOf Me.OnEnvioCorreoElectronico_EstandarSQL_OldOperationCompleted
            End If
            Me.InvokeAsync("EnvioCorreoElectronico_EstandarSQL_Old", New Object() {Destinatario, MailCopia, Asunto, Cuerpo, Formato, Importancia}, Me.EnvioCorreoElectronico_EstandarSQL_OldOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnvioCorreoElectronico_EstandarSQL_OldOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnvioCorreoElectronico_EstandarSQL_OldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnvioCorreoElectronico_EstandarSQL_OldCompleted(Me, New EnvioCorreoElectronico_EstandarSQL_OldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioCorreoElectronico_AplicacionSQL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnvioCorreoElectronico_AplicacionSQL(ByVal IdAplicacion As Integer, ByVal IdMail As Integer, ByVal IdAmbiente As Integer, ByVal Asunto As String, ByVal Cuerpo As String) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnvioCorreoElectronico_AplicacionSQL", New Object() {IdAplicacion, IdMail, IdAmbiente, Asunto, Cuerpo})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_AplicacionSQLAsync(ByVal IdAplicacion As Integer, ByVal IdMail As Integer, ByVal IdAmbiente As Integer, ByVal Asunto As String, ByVal Cuerpo As String)
            Me.EnvioCorreoElectronico_AplicacionSQLAsync(IdAplicacion, IdMail, IdAmbiente, Asunto, Cuerpo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_AplicacionSQLAsync(ByVal IdAplicacion As Integer, ByVal IdMail As Integer, ByVal IdAmbiente As Integer, ByVal Asunto As String, ByVal Cuerpo As String, ByVal userState As Object)
            If (Me.EnvioCorreoElectronico_AplicacionSQLOperationCompleted Is Nothing) Then
                Me.EnvioCorreoElectronico_AplicacionSQLOperationCompleted = AddressOf Me.OnEnvioCorreoElectronico_AplicacionSQLOperationCompleted
            End If
            Me.InvokeAsync("EnvioCorreoElectronico_AplicacionSQL", New Object() {IdAplicacion, IdMail, IdAmbiente, Asunto, Cuerpo}, Me.EnvioCorreoElectronico_AplicacionSQLOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnvioCorreoElectronico_AplicacionSQLOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnvioCorreoElectronico_AplicacionSQLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnvioCorreoElectronico_AplicacionSQLCompleted(Me, New EnvioCorreoElectronico_AplicacionSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronico_Asincrono_Old", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronico_Asincrono_Old(ByVal IdAplicacion As Integer, ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronico_Asincrono_Old", New Object() {IdAplicacion, Destinatarios, Asunto, Cuerpo, Formato, TipoServicio})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Asincrono_OldAsync(ByVal IdAplicacion As Integer, ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio)
            Me.EnviarCorreoElectronico_Asincrono_OldAsync(IdAplicacion, Destinatarios, Asunto, Cuerpo, Formato, TipoServicio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_Asincrono_OldAsync(ByVal IdAplicacion As Integer, ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio, ByVal userState As Object)
            If (Me.EnviarCorreoElectronico_Asincrono_OldOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronico_Asincrono_OldOperationCompleted = AddressOf Me.OnEnviarCorreoElectronico_Asincrono_OldOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronico_Asincrono_Old", New Object() {IdAplicacion, Destinatarios, Asunto, Cuerpo, Formato, TipoServicio}, Me.EnviarCorreoElectronico_Asincrono_OldOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronico_Asincrono_OldOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronico_Asincrono_OldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronico_Asincrono_OldCompleted(Me, New EnviarCorreoElectronico_Asincrono_OldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronicoAdjuntos", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronicoAdjuntos(ByVal MensajeRequest As MensajeAdjuntosRequest) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronicoAdjuntos", New Object() {MensajeRequest})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronicoAdjuntosAsync(ByVal MensajeRequest As MensajeAdjuntosRequest)
            Me.EnviarCorreoElectronicoAdjuntosAsync(MensajeRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronicoAdjuntosAsync(ByVal MensajeRequest As MensajeAdjuntosRequest, ByVal userState As Object)
            If (Me.EnviarCorreoElectronicoAdjuntosOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronicoAdjuntosOperationCompleted = AddressOf Me.OnEnviarCorreoElectronicoAdjuntosOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronicoAdjuntos", New Object() {MensajeRequest}, Me.EnviarCorreoElectronicoAdjuntosOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronicoAdjuntosOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronicoAdjuntosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronicoAdjuntosCompleted(Me, New EnviarCorreoElectronicoAdjuntosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioCorreoElectronico_EstandarSQL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnvioCorreoElectronico_EstandarSQL(ByVal Destinatario As String, ByVal MailCopia As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnvioCorreoElectronico_EstandarSQL", New Object() {Destinatario, MailCopia, Asunto, Cuerpo, Formato, Importancia})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_EstandarSQLAsync(ByVal Destinatario As String, ByVal MailCopia As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String)
            Me.EnvioCorreoElectronico_EstandarSQLAsync(Destinatario, MailCopia, Asunto, Cuerpo, Formato, Importancia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_EstandarSQLAsync(ByVal Destinatario As String, ByVal MailCopia As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String, ByVal userState As Object)
            If (Me.EnvioCorreoElectronico_EstandarSQLOperationCompleted Is Nothing) Then
                Me.EnvioCorreoElectronico_EstandarSQLOperationCompleted = AddressOf Me.OnEnvioCorreoElectronico_EstandarSQLOperationCompleted
            End If
            Me.InvokeAsync("EnvioCorreoElectronico_EstandarSQL", New Object() {Destinatario, MailCopia, Asunto, Cuerpo, Formato, Importancia}, Me.EnvioCorreoElectronico_EstandarSQLOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnvioCorreoElectronico_EstandarSQLOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnvioCorreoElectronico_EstandarSQLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnvioCorreoElectronico_EstandarSQLCompleted(Me, New EnvioCorreoElectronico_EstandarSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoElectronico_Asincrono", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoElectronico_Asincrono(ByVal IdAplicacion As Integer, ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoElectronico_Asincrono", New Object() {IdAplicacion, Destinatarios, Asunto, Cuerpo, Formato, TipoServicio})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_AsincronoAsync(ByVal IdAplicacion As Integer, ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio)
            Me.EnviarCorreoElectronico_AsincronoAsync(IdAplicacion, Destinatarios, Asunto, Cuerpo, Formato, TipoServicio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoElectronico_AsincronoAsync(ByVal IdAplicacion As Integer, ByVal Destinatarios As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As FormatoEMAIL, ByVal TipoServicio As TipoServicio, ByVal userState As Object)
            If (Me.EnviarCorreoElectronico_AsincronoOperationCompleted Is Nothing) Then
                Me.EnviarCorreoElectronico_AsincronoOperationCompleted = AddressOf Me.OnEnviarCorreoElectronico_AsincronoOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoElectronico_Asincrono", New Object() {IdAplicacion, Destinatarios, Asunto, Cuerpo, Formato, TipoServicio}, Me.EnviarCorreoElectronico_AsincronoOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoElectronico_AsincronoOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoElectronico_AsincronoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoElectronico_AsincronoCompleted(Me, New EnviarCorreoElectronico_AsincronoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarCorreoSES", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarCorreoSES(ByVal de As String, ByVal para() As String, ByVal asunto As String, ByVal cuerpo As String, <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByVal adjuntos() As DocumentoAdjunto) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnviarCorreoSES", New Object() {de, para, asunto, cuerpo, adjuntos})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoSESAsync(ByVal de As String, ByVal para() As String, ByVal asunto As String, ByVal cuerpo As String, ByVal adjuntos() As DocumentoAdjunto)
            Me.EnviarCorreoSESAsync(de, para, asunto, cuerpo, adjuntos, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarCorreoSESAsync(ByVal de As String, ByVal para() As String, ByVal asunto As String, ByVal cuerpo As String, ByVal adjuntos() As DocumentoAdjunto, ByVal userState As Object)
            If (Me.EnviarCorreoSESOperationCompleted Is Nothing) Then
                Me.EnviarCorreoSESOperationCompleted = AddressOf Me.OnEnviarCorreoSESOperationCompleted
            End If
            Me.InvokeAsync("EnviarCorreoSES", New Object() {de, para, asunto, cuerpo, adjuntos}, Me.EnviarCorreoSESOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarCorreoSESOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarCorreoSESCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarCorreoSESCompleted(Me, New EnviarCorreoSESCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnvioCorreoElectronico_Portal", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnvioCorreoElectronico_Portal(ByVal Destinatario As String, ByVal CC As String, ByVal CCO As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String) As MensajeResponse
            Dim results() As Object = Me.Invoke("EnvioCorreoElectronico_Portal", New Object() {Destinatario, CC, CCO, Asunto, Cuerpo, Formato, Importancia})
            Return CType(results(0),MensajeResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_PortalAsync(ByVal Destinatario As String, ByVal CC As String, ByVal CCO As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String)
            Me.EnvioCorreoElectronico_PortalAsync(Destinatario, CC, CCO, Asunto, Cuerpo, Formato, Importancia, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnvioCorreoElectronico_PortalAsync(ByVal Destinatario As String, ByVal CC As String, ByVal CCO As String, ByVal Asunto As String, ByVal Cuerpo As String, ByVal Formato As String, ByVal Importancia As String, ByVal userState As Object)
            If (Me.EnvioCorreoElectronico_PortalOperationCompleted Is Nothing) Then
                Me.EnvioCorreoElectronico_PortalOperationCompleted = AddressOf Me.OnEnvioCorreoElectronico_PortalOperationCompleted
            End If
            Me.InvokeAsync("EnvioCorreoElectronico_Portal", New Object() {Destinatario, CC, CCO, Asunto, Cuerpo, Formato, Importancia}, Me.EnvioCorreoElectronico_PortalOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnvioCorreoElectronico_PortalOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnvioCorreoElectronico_PortalCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnvioCorreoElectronico_PortalCompleted(Me, New EnvioCorreoElectronico_PortalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarMensaje", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarMensaje(ByVal EnviarMensaje_MicrobloggingRequest As EnviarMensaje_MicrobloggingRequest) As Mensaje_MicrobloggingResponse
            Dim results() As Object = Me.Invoke("EnviarMensaje", New Object() {EnviarMensaje_MicrobloggingRequest})
            Return CType(results(0),Mensaje_MicrobloggingResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarMensajeAsync(ByVal EnviarMensaje_MicrobloggingRequest As EnviarMensaje_MicrobloggingRequest)
            Me.EnviarMensajeAsync(EnviarMensaje_MicrobloggingRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarMensajeAsync(ByVal EnviarMensaje_MicrobloggingRequest As EnviarMensaje_MicrobloggingRequest, ByVal userState As Object)
            If (Me.EnviarMensajeOperationCompleted Is Nothing) Then
                Me.EnviarMensajeOperationCompleted = AddressOf Me.OnEnviarMensajeOperationCompleted
            End If
            Me.InvokeAsync("EnviarMensaje", New Object() {EnviarMensaje_MicrobloggingRequest}, Me.EnviarMensajeOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarMensajeOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarMensajeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarMensajeCompleted(Me, New EnviarMensajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ComentarMensaje", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ComentarMensaje(ByVal ComentarMensaje_MicrobloggingRequest As ComentarMensaje_MicrobloggingRequest) As Mensaje_MicrobloggingResponse
            Dim results() As Object = Me.Invoke("ComentarMensaje", New Object() {ComentarMensaje_MicrobloggingRequest})
            Return CType(results(0),Mensaje_MicrobloggingResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ComentarMensajeAsync(ByVal ComentarMensaje_MicrobloggingRequest As ComentarMensaje_MicrobloggingRequest)
            Me.ComentarMensajeAsync(ComentarMensaje_MicrobloggingRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ComentarMensajeAsync(ByVal ComentarMensaje_MicrobloggingRequest As ComentarMensaje_MicrobloggingRequest, ByVal userState As Object)
            If (Me.ComentarMensajeOperationCompleted Is Nothing) Then
                Me.ComentarMensajeOperationCompleted = AddressOf Me.OnComentarMensajeOperationCompleted
            End If
            Me.InvokeAsync("ComentarMensaje", New Object() {ComentarMensaje_MicrobloggingRequest}, Me.ComentarMensajeOperationCompleted, userState)
        End Sub
        
        Private Sub OnComentarMensajeOperationCompleted(ByVal arg As Object)
            If (Not (Me.ComentarMensajeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ComentarMensajeCompleted(Me, New ComentarMensajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerMensajesActualizadosTOP20", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerMensajesActualizadosTOP20(ByVal CodigoUsuario As String) As ObtenerMensajes_MicrobloggingResponse
            Dim results() As Object = Me.Invoke("ObtenerMensajesActualizadosTOP20", New Object() {CodigoUsuario})
            Return CType(results(0),ObtenerMensajes_MicrobloggingResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerMensajesActualizadosTOP20Async(ByVal CodigoUsuario As String)
            Me.ObtenerMensajesActualizadosTOP20Async(CodigoUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerMensajesActualizadosTOP20Async(ByVal CodigoUsuario As String, ByVal userState As Object)
            If (Me.ObtenerMensajesActualizadosTOP20OperationCompleted Is Nothing) Then
                Me.ObtenerMensajesActualizadosTOP20OperationCompleted = AddressOf Me.OnObtenerMensajesActualizadosTOP20OperationCompleted
            End If
            Me.InvokeAsync("ObtenerMensajesActualizadosTOP20", New Object() {CodigoUsuario}, Me.ObtenerMensajesActualizadosTOP20OperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerMensajesActualizadosTOP20OperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerMensajesActualizadosTOP20CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerMensajesActualizadosTOP20Completed(Me, New ObtenerMensajesActualizadosTOP20CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerDestinatariosMensaje", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ObtenerDestinatariosMensaje(ByVal CodigoUsuario As String) As ObtenerDestinatariosMensaje_MicrobloggingResponse
            Dim results() As Object = Me.Invoke("ObtenerDestinatariosMensaje", New Object() {CodigoUsuario})
            Return CType(results(0),ObtenerDestinatariosMensaje_MicrobloggingResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ObtenerDestinatariosMensajeAsync(ByVal CodigoUsuario As String)
            Me.ObtenerDestinatariosMensajeAsync(CodigoUsuario, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ObtenerDestinatariosMensajeAsync(ByVal CodigoUsuario As String, ByVal userState As Object)
            If (Me.ObtenerDestinatariosMensajeOperationCompleted Is Nothing) Then
                Me.ObtenerDestinatariosMensajeOperationCompleted = AddressOf Me.OnObtenerDestinatariosMensajeOperationCompleted
            End If
            Me.InvokeAsync("ObtenerDestinatariosMensaje", New Object() {CodigoUsuario}, Me.ObtenerDestinatariosMensajeOperationCompleted, userState)
        End Sub
        
        Private Sub OnObtenerDestinatariosMensajeOperationCompleted(ByVal arg As Object)
            If (Not (Me.ObtenerDestinatariosMensajeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ObtenerDestinatariosMensajeCompleted(Me, New ObtenerDestinatariosMensajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum FormatoEMAIL
        
        '''<remarks/>
        Ninguno
        
        '''<remarks/>
        TEXT
        
        '''<remarks/>
        HTML
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum TipoServicio
        
        '''<remarks/>
        Ninguno
        
        '''<remarks/>
        Transferencias
        
        '''<remarks/>
        AMEX
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MensajeResponse
        
        Private resultadoField As Boolean
        
        Private isErrorField As Boolean
        
        Private descripcionErrorField As String
        
        '''<remarks/>
        Public Property Resultado() As Boolean
            Get
                Return Me.resultadoField
            End Get
            Set
                Me.resultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescripcionError() As String
            Get
                Return Me.descripcionErrorField
            End Get
            Set
                Me.descripcionErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerDestinatariosMensaje_MicrobloggingResponse
        
        Private destinatariosField() As String
        
        Private isErrorField As Boolean
        
        Private descripcionErrorField As String
        
        '''<remarks/>
        Public Property Destinatarios() As String()
            Get
                Return Me.destinatariosField
            End Get
            Set
                Me.destinatariosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescripcionError() As String
            Get
                Return Me.descripcionErrorField
            End Get
            Set
                Me.descripcionErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Mensaje_Microblogging
        
        Private idMensajeField As Integer
        
        Private tipoMensajeField As Integer
        
        Private idMensaje_padreField As Integer
        
        Private mensajeField As String
        
        Private codigoUsuario_RemitenteField As String
        
        Private fechaActualizacionField As Date
        
        Private fechaMensajeField As Date
        
        '''<remarks/>
        Public Property IdMensaje() As Integer
            Get
                Return Me.idMensajeField
            End Get
            Set
                Me.idMensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoMensaje() As Integer
            Get
                Return Me.tipoMensajeField
            End Get
            Set
                Me.tipoMensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IdMensaje_padre() As Integer
            Get
                Return Me.idMensaje_padreField
            End Get
            Set
                Me.idMensaje_padreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUsuario_Remitente() As String
            Get
                Return Me.codigoUsuario_RemitenteField
            End Get
            Set
                Me.codigoUsuario_RemitenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaActualizacion() As Date
            Get
                Return Me.fechaActualizacionField
            End Get
            Set
                Me.fechaActualizacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FechaMensaje() As Date
            Get
                Return Me.fechaMensajeField
            End Get
            Set
                Me.fechaMensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerMensajes_MicrobloggingResponse
        
        Private mensajesField() As Mensaje_Microblogging
        
        Private isErrorField As Boolean
        
        Private descripcionErrorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Mensajes() As Mensaje_Microblogging()
            Get
                Return Me.mensajesField
            End Get
            Set
                Me.mensajesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescripcionError() As String
            Get
                Return Me.descripcionErrorField
            End Get
            Set
                Me.descripcionErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ComentarMensaje_MicrobloggingRequest
        
        Private idMensaje_padreField As Integer
        
        Private codigoUsuario_RemitenteField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        Public Property IdMensaje_padre() As Integer
            Get
                Return Me.idMensaje_padreField
            End Get
            Set
                Me.idMensaje_padreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodigoUsuario_Remitente() As String
            Get
                Return Me.codigoUsuario_RemitenteField
            End Get
            Set
                Me.codigoUsuario_RemitenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Mensaje_MicrobloggingResponse
        
        Private idMensajeField As Integer
        
        Private isErrorField As Boolean
        
        Private descripcionErrorField As String
        
        '''<remarks/>
        Public Property IdMensaje() As Integer
            Get
                Return Me.idMensajeField
            End Get
            Set
                Me.idMensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsError() As Boolean
            Get
                Return Me.isErrorField
            End Get
            Set
                Me.isErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DescripcionError() As String
            Get
                Return Me.descripcionErrorField
            End Get
            Set
                Me.descripcionErrorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarMensaje_MicrobloggingRequest
        
        Private codigoUsuario_RemitenteField As String
        
        Private mensajeField As String
        
        Private destinatariosField() As String
        
        '''<remarks/>
        Public Property CodigoUsuario_Remitente() As String
            Get
                Return Me.codigoUsuario_RemitenteField
            End Get
            Set
                Me.codigoUsuario_RemitenteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Destinatarios() As String()
            Get
                Return Me.destinatariosField
            End Get
            Set
                Me.destinatariosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DocumentoAdjunto
        
        Private nombreField As String
        
        Private contenidoField() As Byte
        
        '''<remarks/>
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Contenido() As Byte()
            Get
                Return Me.contenidoField
            End Get
            Set
                Me.contenidoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MensajeAdjuntosRequest
        
        Private destinatariosField As String
        
        Private asuntoField As String
        
        Private cuerpoField As String
        
        Private adjuntosField() As DocumentoAdjunto
        
        Private formatoField As FormatoEMAIL
        
        Private tipoServicioField As TipoServicio
        
        '''<remarks/>
        Public Property Destinatarios() As String
            Get
                Return Me.destinatariosField
            End Get
            Set
                Me.destinatariosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Asunto() As String
            Get
                Return Me.asuntoField
            End Get
            Set
                Me.asuntoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cuerpo() As String
            Get
                Return Me.cuerpoField
            End Get
            Set
                Me.cuerpoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property Adjuntos() As DocumentoAdjunto()
            Get
                Return Me.adjuntosField
            End Get
            Set
                Me.adjuntosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Formato() As FormatoEMAIL
            Get
                Return Me.formatoField
            End Get
            Set
                Me.formatoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoServicio() As TipoServicio
            Get
                Return Me.tipoServicioField
            End Get
            Set
                Me.tipoServicioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class MensajeRequest
        
        Private destinatariosField As String
        
        Private asuntoField As String
        
        Private cuerpoField As String
        
        Private contenidoDocumento1Field() As Byte
        
        Private nombreDocumento1Field As String
        
        Private formatoField As FormatoEMAIL
        
        Private tipoServicioField As TipoServicio
        
        '''<remarks/>
        Public Property Destinatarios() As String
            Get
                Return Me.destinatariosField
            End Get
            Set
                Me.destinatariosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Asunto() As String
            Get
                Return Me.asuntoField
            End Get
            Set
                Me.asuntoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cuerpo() As String
            Get
                Return Me.cuerpoField
            End Get
            Set
                Me.cuerpoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property ContenidoDocumento1() As Byte()
            Get
                Return Me.contenidoDocumento1Field
            End Get
            Set
                Me.contenidoDocumento1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NombreDocumento1() As String
            Get
                Return Me.nombreDocumento1Field
            End Get
            Set
                Me.nombreDocumento1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Formato() As FormatoEMAIL
            Get
                Return Me.formatoField
            End Get
            Set
                Me.formatoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TipoServicio() As TipoServicio
            Get
                Return Me.tipoServicioField
            End Get
            Set
                Me.tipoServicioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronico_Mail_OldCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronico_Mail_OldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronico_Mail_OldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronico_MailCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronico_MailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronico_MailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronico_SQL_ServerCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronico_SQL_ServerCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronico_SQL_ServerCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnvioCorreoElectronico_AFEXCompletedEventHandler(ByVal sender As Object, ByVal e As EnvioCorreoElectronico_AFEXCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnvioCorreoElectronico_AFEXCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronico_Mail_2_OldCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronico_Mail_2_OldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronico_Mail_2_OldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronico_Mail_2CompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronico_Mail_2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronico_Mail_2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronicoAdjuntos_OldCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronicoAdjuntos_OldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronicoAdjuntos_OldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnvioCorreoElectronico_EstandarSQL_OldCompletedEventHandler(ByVal sender As Object, ByVal e As EnvioCorreoElectronico_EstandarSQL_OldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnvioCorreoElectronico_EstandarSQL_OldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnvioCorreoElectronico_AplicacionSQLCompletedEventHandler(ByVal sender As Object, ByVal e As EnvioCorreoElectronico_AplicacionSQLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnvioCorreoElectronico_AplicacionSQLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronico_Asincrono_OldCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronico_Asincrono_OldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronico_Asincrono_OldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronicoAdjuntosCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronicoAdjuntosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronicoAdjuntosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnvioCorreoElectronico_EstandarSQLCompletedEventHandler(ByVal sender As Object, ByVal e As EnvioCorreoElectronico_EstandarSQLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnvioCorreoElectronico_EstandarSQLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoElectronico_AsincronoCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoElectronico_AsincronoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoElectronico_AsincronoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarCorreoSESCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarCorreoSESCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarCorreoSESCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnvioCorreoElectronico_PortalCompletedEventHandler(ByVal sender As Object, ByVal e As EnvioCorreoElectronico_PortalCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnvioCorreoElectronico_PortalCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MensajeResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MensajeResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub EnviarMensajeCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarMensajeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarMensajeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Mensaje_MicrobloggingResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Mensaje_MicrobloggingResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub ComentarMensajeCompletedEventHandler(ByVal sender As Object, ByVal e As ComentarMensajeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ComentarMensajeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Mensaje_MicrobloggingResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Mensaje_MicrobloggingResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub ObtenerMensajesActualizadosTOP20CompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerMensajesActualizadosTOP20CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerMensajesActualizadosTOP20CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ObtenerMensajes_MicrobloggingResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ObtenerMensajes_MicrobloggingResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub ObtenerDestinatariosMensajeCompletedEventHandler(ByVal sender As Object, ByVal e As ObtenerDestinatariosMensajeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ObtenerDestinatariosMensajeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ObtenerDestinatariosMensaje_MicrobloggingResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ObtenerDestinatariosMensaje_MicrobloggingResponse)
            End Get
        End Property
    End Class
End Namespace
